### PR TITLE
Allow purchase of items in shops using BUY action

### PR DESCRIPTION
**Pull request by ayoung012**
This PR makes changes to the massim server and to the eismassim package.

@ssardina Yet to be adjusted is the version of this new 2018 server package. The version should reflect that this is a modified version of the 2018 server and eismassim package with items in shops functionality added.

Any projects that rely on eismassim, including sarl-agtcity-mw and sarl-agtcity-jas, will need to update their pom dependencies to the updated version present here.

### CODE REVIEW

**Comment by ayoung012** [comment]
@ssardina note that we will need to make the same decision here as we did for the 2017-2018 migration. The sarl-agtcity-mw project will need to specify the version of eismassim it will work with. The new version of eismassim in this pull request supports items in shops, whereas the original 2018 version does not.

**Comment by ssardina** [comment]
OK I see, this repo already contains eismassim, which is the API that allows talking to the updated server, now I get it :-)

**Comment by ssardina** [comment]
If we update the version, I think it is ready to merge on master

**Comment by ayoung012** [comment]
@ssardina You already updated the version a few months ago, however I'm not sure that it has been made clear this is a separate project to massim

This repository represents 'MASSim' as a whole. The subfolders are sub-projects. The items in shops change has only affected sub-projects:
* eismassim
* protocol
* server

These need new versions, and I propose changing either the groupid or artifact id to differentiate it from the official MASSim project in maven.

Something like this:
```
    <groupId>ssardina-agts.massim</groupId>
    <artifactId>server</artifactId>
    <version>2.0</version>
```
etc...

**Comment by ayoung012** [comment]
Seems like this has been addressed in https://github.com/ssardina-agts/agtcity-server/issues/3, but I cannot see where the groupId has been updated?

**Comment by ssardina** [comment]
But the branch `origin/feature/items-in-shops,` is ahead of `master` as far as I can see..

You are right, the pom is not changed. What about this:

```
  <groupId>ssardina-agts.massim</groupId>
  <artifactId>agtcity-server</artifactId>
  <version>2020-1.0</version>
``` 

And changed all modules accordingly and put all versions of every module as `2020-1.0` for uniformity, and we start from there us.

There are other ways, but are you ok with all this?

what is `eishub` ? Do we depend on any other EI package outside our repo?

**Comment by ayoung012** [comment]
Does the groupId need to be com.github.ssardina-agts.agtcity-server? for JitPack?

**Comment by ayoung012** [comment]
eishub is an external dependancy that provides the generic Percept type, no changes were made to it

**Comment by ssardina** [comment]
Thanks, I have drop your  explanation in the [server repo Wiki](https://github.com/ssardina-agts/agtcity-server/wiki/_new). We need to collect all this non-trivial info that you have learnt for the future for us and new people. Thanks

**Comment by ssardina** [comment]
> Does the groupId need to be com.github.ssardina-agts.agtcity-server? for JitPack?

mm this is the server, what do we need to gather from here from jitpack? the `eismassim` module ?

I don't remember JitPack, will check now but there were some format to get it from github automatically I remember.. I will check this now and complete the naming

**Comment by ssardina** [comment]
@ayoung012 , have changed all project names and versions. 

Now, it seems one may not need JitPack. See how they have configured to get `eihub`:

```
    <repositories>
        <repository>
            <id>eishub-mvn-repo</id>
            <url>https://raw.github.com/eishub/mvn-repo/master</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>eishub</groupId>
            <artifactId>eis</artifactId>
            <version>0.6.0</version>
        </dependency>

```

**Comment by ayoung012** [comment]
Very nice. Do we need to configure releases for this to work?

**Comment by ssardina** [comment]
forget it, it is not very neat. It requires to maintain a dedicated repo with JAR files, not nice:

https://gist.github.com/fernandezpablo85/03cf8b0cd2e7d8527063

There is is also discussed that the GitHub Maven support is still not great. 

So, better stay with JitPack. The MW has to get the `eismassim` (and its `protocol`) dependency from this server only. 

All is working with the new server. So no worries.

**Comment by ssardina** [comment]
I think this can be merged, I have used it quite a bit. Has the updated project id too, to make it different from the original massim. I have used:

```
 <groupId>ssardina-agts.massim</groupId>
    <artifactId>eismassim</artifactId>
    <version>2020-1.0</version>
```

and use  `2020-1.0` for all modules as well.

Tested the MW and works, via Jitpack.

**Pull request merged**
